config/routes.rb
Rails.application.routes.draw do
  resources :centros
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/centro.rb
class Centro < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/centros_controller.rb
class CentrosController < ApplicationController
  before_action :set_centro, only: %i[ show edit update destroy ]

  # GET /centros or /centros.json
  def index
    @centros = Centro.all
  end

  # GET /centros/1 or /centros/1.json
  def show
  end

  # GET /centros/new
  def new
    @centro = Centro.new
  end

  # GET /centros/1/edit
  def edit
  end

  # POST /centros or /centros.json
  def create
    @centro = Centro.new(centro_params)

    respond_to do |format|
      if @centro.save
        format.html { redirect_to centro_url(@centro), notice: "Centro was successfully created." }
        format.json { render :show, status: :created, location: @centro }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @centro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /centros/1 or /centros/1.json
  def update
    respond_to do |format|
      if @centro.update(centro_params)
        format.html { redirect_to centro_url(@centro), notice: "Centro was successfully updated." }
        format.json { render :show, status: :ok, location: @centro }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @centro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /centros/1 or /centros/1.json
  def destroy
    @centro.destroy!

    respond_to do |format|
      format.html { redirect_to centros_url, notice: "Centro was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_centro
      @centro = Centro.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def centro_params
      params.require(:centro).permit(:sigla, :nome)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/centros_helper.rb
module CentrosHelper
end

app/views/centros/_centro.html.erb
<div id="<%= dom_id centro %>">
  <p>
    <strong>Sigla:</strong>
    <%= centro.sigla %>
  </p>

  <p>
    <strong>Nome:</strong>
    <%= centro.nome %>
  </p>

</div>

app/views/centros/_form.html.erb
<%= form_with(model: centro) do |form| %>
  <% if centro.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(centro.errors.count, "error") %> prohibited this centro from being saved:</h2>

      <ul>
        <% centro.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :sigla, style: "display: block" %>
    <%= form.text_field :sigla %>
  </div>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/centros/edit.html.erb
<h1>Editing centro</h1>

<%= render "form", centro: @centro %>

<br>

<div>
  <%= link_to "Show this centro", @centro %> |
  <%= link_to "Back to centros", centros_path %>
</div>

app/views/centros/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Centros</h1>

<div id="centros">
  <% @centros.each do |centro| %>
    <%= render centro %>
    <p>
      <%= link_to "Show this centro", centro %>
    </p>
  <% end %>
</div>

<%= link_to "New centro", new_centro_path %>

app/views/centros/new.html.erb
<h1>New centro</h1>

<%= render "form", centro: @centro %>

<br>

<div>
  <%= link_to "Back to centros", centros_path %>
</div>

app/views/centros/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @centro %>

<div>
  <%= link_to "Edit this centro", edit_centro_path(@centro) %> |
  <%= link_to "Back to centros", centros_path %>

  <%= button_to "Destroy this centro", @centro, method: :delete %>
</div>

app/views/home/index.html.erb
<%= link_to "New centro", new_centro_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Residencia</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">

  <div class="container-fluid">
    <a class="navbar-brand" href="#">VET</a>
    <!-- Links -->
<div class="collapse navbar-collapse" id="collapsibleNavbar">
    <ul class="navbar-nav">

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown">Cadastro</a>
        <ul class="dropdown-menu">
          <li><a class="dropdown-item" href="#">Centro</a></li>
          <li><a class="dropdown-item" href="#">Another link</a></li>
          <li><a class="dropdown-item" href="#">A third link</a></li>
        </ul>
      </li>
    </ul>
  </div>
</div>
</nav>
<div class="container-fluid" style="margin-top:80px">
  <body>
    <%= yield %>
  </body>
</div>
</html>